language: go
go:
  - "1.16"
install:
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/stretchr/testify/assert
script:
  - go test -v -covermode=count -coverprofile=profile.cov
after_success:
  - go get -v github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin
  - goveralls -coverprofile=profile.cov -service=travis-ci